name: Build project
on: [push]
jobs:

  buildForWebGL:

    name: Build for WebGL 🕸

    runs-on: ubuntu-latest

    steps:

      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Activate Unity
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}      

      # Configure builder
      - name: Build project
        id: buildStep
        uses: webbertakken/unity-builder@v0.3
        with:
          projectPath: LaserDefender
          unityVersion: 2018.3.0f2
          targetPlatform: WebGL
          buildsPath: Build

      # Upload distributables
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: ${{ steps.buildStep.outputs.buildPath }}
