name: CI

on: [push]

jobs:
  buildForWebGL:
    name: Build for WebGL 🕸
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1
        
      # Configure Builder
      - name: Build project
        id: buildStep
        uses: webbertakken/unity-builder@v0.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: .
          BUILD_NAME: TestBuild
          BUILD_TARGET: WebGL
          BUILDS_PATH: builds
          BUILD_COMMAND: ""
          
      # Upload distributables
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: ${{ steps.buildStep.outputs.allBuildsPath }}
