name: Actions 😎

on: [push]

env:
  BUILD_NAME: LaserDefender
  UNITY_LICENSE_CONTENT: ${{ secrets.UNITY_LICENSE_2018 }}
  UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:

  buildForWebGL:
    name: Build Laser Defender for WebGL 🕸
    runs-on: ubuntu-latest
    env:
      BUILD_TARGET: WebGL
      IMAGE_NAME: gableroux/unity3d:2018.3.0f2-webgl
      UNITY_ACTIVATION_FILE: ./unity3d.alf

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: Builds/$BUILD_TARGET

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          # Build directory to deploy
          build_dir: Builds/$BUILD_TARGET